### ISSUE TITLE
Error when POSTing: Response' object has no attribute 'status'

### ISSUE THREAD

**Issue by marcomusso** [smetj/wishbone-output-http#4]
I get `'Response' object has no attribute 'status'` when posting to an API.

It seems that in the case of an exception it hits line [118](https://github.com/smetj/wishbone-output-http/blob/master/wishbone_output_http/httpoutclient.py#L118). I tried putting `status_code` instead of `status` and I got the reason of the failure when POSTing.

**Comment by smetj** [comment]
Yes, I believe that has been fixed here: https://github.com/smetj/wishbone-output-http/commit/c47ef0329633f3e328dc1508e788148fe035813f#diff-0731ec530e51c9d1716224b16af02a52R122

I have released version 1.2.0 (including pypi).

Thanks for the report!
